twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        sitename: "%env(SITENAME)%"
        app_env: "%env(APP_ENV)%"
    form_themes: ['bootstrap_4_layout.html.twig']
    number_format:
        decimals: 2
        decimal_point: '.'
        thousands_separator: ''
