name: Symfony

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: PHP ${{ matrix.php-versions }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@2.5.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v1
          extension: mbstring, xml, ctype, iconv, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, phar, fileinfo
          # Have the execution time in sync with composer.json -> config.process-timeout.
          ini-values: memory_limit=1024M, max_execution_time=1200, max_input_time=1200, post_max_size=256M, short_open_tag=On #optional
          coverage: none
      - uses: actions/checkout@v2
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Running tests
        run: composer run tests
